### ISSUE TITLE
"Relaton XML" links missing on site

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/standards.calconnect.org#27]
Currently on https://standards.calconnect.org/standards/ or https://staging.standards.calconnect.org/standards/ , clicking on "Relaton XML" will bring you back to the main page instead of the XML (but the file exists).

e.g. https://staging.standards.calconnect.org/csd/cc-10100.rxl works. But in its entry on https://staging.standards.calconnect.org/standards/ , the "Relaton XML" link is broken.

@abunashir could you help with this? Thanks!

**Comment by abunashir** [comment]
I'm on it :)
