### ISSUE TITLE
Host site at GitHub Pages

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/standards.calconnect.org#40]
GitHub Pages is free and easy to manage without any infrastructure costs. It is well integrated with GitHub repositories and GitHub Actions.

I think we should move this site (and also all the *.calconnect.org sites) to GitHub Pages.

Thoughts?

**Comment by wsdwl** [comment]
I would have no objections.

**Comment by ronaldtse** [comment]
I will proceed with this task here:
* https://github.com/CalConnect/calconnect.org/issues/1

**Comment by ronaldtse** [comment]
I have discussed with @douglm that this site is to be moved to GitHub Pages.

We will first move the deployment and then @douglm will update the DNS.

@kwkwan can you please help migrate this site (and deployment) to GitHub Pages? Some modernization is necessary due to the updates we have made to Metanorma the past few years...

Thanks!

**Comment by kwkwan** [comment]
@ronaldtse I have committed some changes to deploy the site.  However, I do not have privileges to enable the Github Pages.  Please assign me the proper permissions or someone responsible to manage this repo to setup Github Pages before setting up the DNS records.

**Comment by ronaldtse** [comment]
@kwkwan you have full access now. Thanks!

**Comment by kwkwan** [comment]
Hi @ronaldtse The site has been deployed to Github Pages at https://calconnect.github.io/standards.calconnect.org/.  Please note that the css style is incorrect because they are based on root folder.  I think this issue will be fixed after configuring the custom domain for Github Pages.

Hi @douglm, please setup the CNAME record for `standards.calconnect.org` to `calconnect.github.io` in order to setup the custom domain for Github Pages.

**Comment by ronaldtse** [comment]
@douglm the documentation is located here, or we can do the setup for you:

* https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by douglm** [comment]
OK - standards.calconnect.org was unreachable after I added calconnect.org to aws route53.
I've added a cname as above and I get a security warning for the cert - it's a github.io cert not calconect.org

**Comment by kwkwan** [comment]
Hi @douglm and @ronaldtse I have updated the custom domain settings in GitHub and it should be working now.

<img width="1571" alt="Screenshot 2024-12-20 at 12 48 20 PM" src="https://github.com/user-attachments/assets/b251d52a-1ea3-485d-9209-2be1f0863b21" />

<img width="1571" alt="Screenshot 2024-12-20 at 12 48 53 PM" src="https://github.com/user-attachments/assets/5ad097b0-b364-4424-a43e-b5cd1b3cafe5" />

**Comment by kwkwan** [comment]
Closed #40 as completed.
